version: '3'

services:
  server:
    container_name: java
    build:
      context: .
    image: amazoncorretto:11
    volumes: # 공유할 볼륨
      - /home/app/projects/:/home/projects
    ports: # 열어 둘 포트
      - 50001:8080
    command: ['java','-jar', '-Dspring.active.profiles=prod', '/home/projects/application.war']
